#!/bin/bash
gcc -Wall -g -o hello hello.c -lyang -I /usr/local/include/libyang/ && ./hello
echo '<?xml version="1.0"?><data>' >/tmp/x.xml
cat /tmp/libyang.xml >>/tmp/x.xml
echo '</data>' >>/tmp/x.xml
xmllint --format /tmp/x.xml
